<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edcCoreFunction.proto

namespace WebEDC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WebEDC.LoginResponse</code>
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string jwt = 2;</code>
     */
    protected $jwt = '';
    /**
     * Generated from protobuf field <code>bool isadmin = 3;</code>
     */
    protected $isadmin = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $jwt
     *     @type bool $isadmin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EdcCoreFunction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jwt = 2;</code>
     * @return string
     */
    public function getJwt()
    {
        return $this->jwt;
    }

    /**
     * Generated from protobuf field <code>string jwt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJwt($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isadmin = 3;</code>
     * @return bool
     */
    public function getIsadmin()
    {
        return $this->isadmin;
    }

    /**
     * Generated from protobuf field <code>bool isadmin = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsadmin($var)
    {
        GPBUtil::checkBool($var);
        $this->isadmin = $var;

        return $this;
    }

}

