<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edcCoreFunction.proto

namespace WebEDC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WebEDC.SeeAllTransactionList</code>
 */
class SeeAllTransactionList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transactionid = 1;</code>
     */
    protected $transactionid = '';
    /**
     * Generated from protobuf field <code>string platenumber = 2;</code>
     */
    protected $platenumber = '';
    /**
     * Generated from protobuf field <code>string vehicletype = 3;</code>
     */
    protected $vehicletype = '';
    /**
     * Generated from protobuf field <code>string intime = 4;</code>
     */
    protected $intime = '';
    /**
     * Generated from protobuf field <code>string outtime = 5;</code>
     */
    protected $outtime = '';
    /**
     * Generated from protobuf field <code>double price = 6;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>string edcidin = 7;</code>
     */
    protected $edcidin = '';
    /**
     * Generated from protobuf field <code>string edcidout = 8;</code>
     */
    protected $edcidout = '';
    /**
     * Generated from protobuf field <code>string operatorin = 9;</code>
     */
    protected $operatorin = '';
    /**
     * Generated from protobuf field <code>string operatorout = 10;</code>
     */
    protected $operatorout = '';
    /**
     * Generated from protobuf field <code>bool isdone = 11;</code>
     */
    protected $isdone = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transactionid
     *     @type string $platenumber
     *     @type string $vehicletype
     *     @type string $intime
     *     @type string $outtime
     *     @type float $price
     *     @type string $edcidin
     *     @type string $edcidout
     *     @type string $operatorin
     *     @type string $operatorout
     *     @type bool $isdone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EdcCoreFunction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transactionid = 1;</code>
     * @return string
     */
    public function getTransactionid()
    {
        return $this->transactionid;
    }

    /**
     * Generated from protobuf field <code>string transactionid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->transactionid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platenumber = 2;</code>
     * @return string
     */
    public function getPlatenumber()
    {
        return $this->platenumber;
    }

    /**
     * Generated from protobuf field <code>string platenumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatenumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->platenumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vehicletype = 3;</code>
     * @return string
     */
    public function getVehicletype()
    {
        return $this->vehicletype;
    }

    /**
     * Generated from protobuf field <code>string vehicletype = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVehicletype($var)
    {
        GPBUtil::checkString($var, True);
        $this->vehicletype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string intime = 4;</code>
     * @return string
     */
    public function getIntime()
    {
        return $this->intime;
    }

    /**
     * Generated from protobuf field <code>string intime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIntime($var)
    {
        GPBUtil::checkString($var, True);
        $this->intime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string outtime = 5;</code>
     * @return string
     */
    public function getOuttime()
    {
        return $this->outtime;
    }

    /**
     * Generated from protobuf field <code>string outtime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOuttime($var)
    {
        GPBUtil::checkString($var, True);
        $this->outtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 6;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string edcidin = 7;</code>
     * @return string
     */
    public function getEdcidin()
    {
        return $this->edcidin;
    }

    /**
     * Generated from protobuf field <code>string edcidin = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEdcidin($var)
    {
        GPBUtil::checkString($var, True);
        $this->edcidin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string edcidout = 8;</code>
     * @return string
     */
    public function getEdcidout()
    {
        return $this->edcidout;
    }

    /**
     * Generated from protobuf field <code>string edcidout = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEdcidout($var)
    {
        GPBUtil::checkString($var, True);
        $this->edcidout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operatorin = 9;</code>
     * @return string
     */
    public function getOperatorin()
    {
        return $this->operatorin;
    }

    /**
     * Generated from protobuf field <code>string operatorin = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOperatorin($var)
    {
        GPBUtil::checkString($var, True);
        $this->operatorin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operatorout = 10;</code>
     * @return string
     */
    public function getOperatorout()
    {
        return $this->operatorout;
    }

    /**
     * Generated from protobuf field <code>string operatorout = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOperatorout($var)
    {
        GPBUtil::checkString($var, True);
        $this->operatorout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isdone = 11;</code>
     * @return bool
     */
    public function getIsdone()
    {
        return $this->isdone;
    }

    /**
     * Generated from protobuf field <code>bool isdone = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsdone($var)
    {
        GPBUtil::checkBool($var);
        $this->isdone = $var;

        return $this;
    }

}

